# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-amplify-app
  description: Terraform module to provision AWS Amplify apps, backend environments, branches, domain associations, and webhooks
  homepage: https://cloudposse.com/accelerate
  topics: amplify, branch, domain, webhook


